Fix compilation error (Erlang 24x) and likely bug.
Likely bug (see https://github.com/chef/opscoderl_httpc/pull/14 for
context):

===> Compiling src/oc_time.erl failed
src/oc_time.erl:32:1: this clause for to_ms/2 cannot match because a previous clause at line 30 always matches
src/oc_time.erl:34:1: this clause for to_ms/2 cannot match because a previous clause at line 30 always matches

Compilation error Erlang 24x:

===> Compiling _build/default/lib/opscoderl_httpc/src/oc_time.erl failed
_build/default/lib/opscoderl_httpc/src/oc_time.erl:30:7: variable '_Unit' is bound multiple times in this pattern. If you mean to ignore this value, use '_' or a different underscore-prefixed name
_build/default/lib/opscoderl_httpc/src/oc_time.erl:30:14: variable '_Unit' is bound multiple times in this pattern. If you mean to ignore this value, use '_' or a different underscore-prefixed name

Signed-off-by: Lincoln Baker <lbaker@chef.io>